### ISSUE TITLE
上传文件报错

### ISSUE THREAD

**Issue by Macrow** [netless-io/netless-react-whiteboard#101]
在上传图片时会报错，根据提示发现```UploadManager.tsx```文件中
```
this.room.setMemberState({
      currentApplianceName: ApplianceNames.selector,
 });
```
这里会报错，提示```undefine.selector```找不到

**Comment by leavesster** [comment]
部分低版本存在 Appliance 类型未导出，只能使用字符串"selector"的情况，升级或者查看 developer.netless.link 中选择修复问题的版本即可。
